# Generated by Django 2.2.6 on 2022-01-01 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='bode',
            new_name='body',
        ),
    ]
